spring:
  application:
    name: csi-plugin

grpc:
  server:
    port: 50051

hdfs:
  url: ${HDFS_URL:hdfs://namenode:8020} # Priorise la variable d'env HDFS_URL ou utilise une valeur par d√©faut
  user: ${HDFS_USER:hdfs_user}