apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hdfs-csi-binding
subjects:
  - kind: ServiceAccount
    name: hdfs-csi-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hdfs-csi-role
  apiGroup: rbac.authorization.k8s.io