apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-csi-plugin
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hdfs-csi-plugin
  template:
    metadata:
      labels:
        app: hdfs-csi-plugin
    spec:
      serviceAccountName: hdfs-csi-sa
      containers:
        - name: hdfs-csi-plugin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CSI_ENDPOINT
              value: "unix:///csi/csi.sock"
          ports:
            - name: grpc
              containerPort: {{ .Values.grpcPort }}
              protocol: TCP
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
      volumes:
        - name: csi-socket-dir
          emptyDir: {}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}