apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hdfs-csi-plugin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: hdfs-csi-plugin
  template:
    metadata:
      labels:
        app: hdfs-csi-plugin
    spec:
      serviceAccountName: hdfs-csi-sa
      containers:
        - name: hdfs-csi-plugin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CSI_ENDPOINT
              value: "unix:///var/lib/kubelet/plugins/hdfs.csi.varga/csi.sock"
            - name: SERVICE_ACCOUNT_NAME
              value: {{ .Values.back.serviceaccount }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: host-path-socket
              mountPath: /var/lib/kubelet/plugins/hdfs.csi.varga
              mountPropagation: Bidirectional
          securityContext:
            privileged: true
      volumes:
        - name: host-path-socket
          hostPath:
            path: /var/lib/kubelet/plugins/hdfs.csi.varga
            type: DirectoryOrCreate
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}